version: 3
shell_integration: true
enable_cursor_positioning: true
async: true
final_space: true

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: path
        properties:
          style: full
  - type: prompt
    alignment: left
    segments:
      - type: git
        style: plain
        foreground: "#ffffff"
      - type: status
        style: plain
        foreground: green
        template: " {{ if .Segments.Git.UpstreamGone }}î¬…{{ end }} "
      - type: status
        style: plain
        foreground: red
        template: " {{ if gt .Code 0 }}<b>[{{ .Code }}]</b>{{ end }}"
