---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      ansible_user: "{{ lookup('env', 'USER') }}"
      ansible_home: "{{ lookup('env', 'HOME') }}"
  
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    dotfiles_dir: "{{ lookup('env', 'HOME') }}/.dotfiles"
